### ISSUE TITLE
Síntesis 

### ISSUE THREAD

**Issue by JazminloRI** [SistemasTecTlaxiaco/actividad-3-sintesis-JazminloRI#2]
[Infografia_JazminLR.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-sintesis-JazminloRI/files/9464541/Infografia_JazminLR.pdf)

**Comment by Nayee123** [comment]
20/20 buen trabajo

**Comment by josealfredo79** [comment]
Bien hecho y revisado
